// Full task (what the backend returns)
export interface Task {
  id: number; // generated by backend
  caseId: number;
  title: string;
  description?: string;
  status: string;
  dueDateTime: string;
  createdAt: string;
  updatedAt: string;
}

// Input type (what we send when creating a task)
export type TaskCreate = Omit<Task, 'id' | 'createdAt' | 'updatedAt'>;

// Update type (what we send when updating a task)
export type TaskUpdate = Partial<TaskCreate>;
